In [1]:
import numpy as np


def mtx_similar(arr1: np.ndarray, arr2: np.ndarray) -> float:
    '''
    计算矩阵相似度的一种方法。将矩阵展平成向量，计算向量的乘积除以模长。
    注意有展平操作。
    :param arr1:矩阵1
    :param arr2:矩阵2
    :return:实际是夹角的余弦值，ret = (cos+1)/2
    '''
    farr1 = arr1.ravel()
    farr2 = arr2.ravel()
    len1 = len(farr1)
    len2 = len(farr2)
    if len1 > len2:
        farr1 = farr1[:len2]
    else:
        farr2 = farr2[:len1]

    numer = np.sum(farr1 * farr2)
    denom = np.sqrt(np.sum(farr1**2) * np.sum(farr2**2))
    similar = numer / denom  # 这实际是夹角的余弦值
    return (similar + 1) / 2  # 姑且把余弦函数当线性

In [4]:
#这里是做一个示范，用0到13之间的14个数字组合成了6个矩阵来做演示。
mtx_list = []
for i in range(6):
    mtx_list.append(np.arange(i, i + 9).reshape(3, 3))
print(mtx_list)

[array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]]), array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]]), array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]]), array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]]), array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])]


In [5]:
#应用上面的函数来算出相似度矩阵。
l = len(mtx_list)
sim_mtx = np.zeros((l, l))
for i in range(l):
    for j in range(l):
        sim_mtx[i][j] = mtx_similar(mtx_list[i], mtx_list[j])
print(sim_mtx)

[[ 1.          0.9976726   0.99305843  0.98796722  0.98306504  0.97857239]
 [ 0.9976726   1.          0.99876492  0.99620368  0.99325138  0.99030015]
 [ 0.99305843  0.99876492  1.          0.99929779  0.997784    0.99597357]
 [ 0.98796722  0.99620368  0.99929779  1.          0.99957614  0.99863204]
 [ 0.98306504  0.99325138  0.997784    0.99957614  1.          0.9997309 ]
 [ 0.97857239  0.99030015  0.99597357  0.99863204  0.9997309   1.        ]]


In [6]:
#把结果在减去单位阵
sim_mtx = sim_mtx - np.eye(l)
print(sim_mtx)

[[ 0.          0.9976726   0.99305843  0.98796722  0.98306504  0.97857239]
 [ 0.9976726   0.          0.99876492  0.99620368  0.99325138  0.99030015]
 [ 0.99305843  0.99876492  0.          0.99929779  0.997784    0.99597357]
 [ 0.98796722  0.99620368  0.99929779  0.          0.99957614  0.99863204]
 [ 0.98306504  0.99325138  0.997784    0.99957614  0.          0.9997309 ]
 [ 0.97857239  0.99030015  0.99597357  0.99863204  0.9997309   0.        ]]
